services:
  # nginx service
  nginx:
    command: ["sleep", "infinity"]
    depends_on:
      - backend
    container_name: "nginx"
    restart: unless-stopped
    build:
      context: react_main
      dockerfile: dockerfile
      target: production
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - my_net
  certbot:
    image: certbot/certbot
    container_name: "certbot"
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
